version: '3.1'
services:
  papercut:
      build: .
      restart: always
      depends_on:
        - mysql
      links:
        - mysql:database
      ports:
        - 9191:9191
        - 9192:9192
        - 9193:9193
        - 9631:631
      volumes:
        - papercut_logs:/papercut/server/logs
        - papercut_conf:/papercut/server/data/conf
        - papercut_custom:/papercut/server/custom
        - papercut_backups:/papercut/server/data/backups
        - papercut_archive:/papercut/server/data/archive
      environment:
        PAPERCUT_ADMIN_USERNAME: admin
        PAPERCUT_ADMIN_PASSWORD: admin
        PAPERCUT_DATABASE_TYPE: MySQL
        PAPERCUT_DATABASE_DRIVER: com.mysql.cj.jdbc.Driver
        PAPERCUT_DATABASE_USERNAME: papercut
        PAPERCUT_DATABASE_PASSWORD: papercut
        PAPERCUT_DATABASE_URL: jdbc:mysql://database:3306/papercut?useSSL=false
  mysql:
      image: mysql:5.7
      restart: always
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: papercut
        MYSQL_DATABASE: papercut
        MYSQL_USER: papercut
        MYSQL_PASSWORD: papercut
  phpmyadmin:
      image: phpmyadmin:5.0.2
      restart: always
      depends_on:
          - mysql
      ports:
          - 8080:80
      environment:
          MYSQL_ROOT_PASSWORD: papercut
          PMA_HOST: mysql
volumes:
  papercut_logs:
  papercut_conf:
  papercut_custom:
  papercut_backups:
  papercut_archive:
